### ISSUE TITLE
Lower bound of speed filter doesn't work

### ISSUE THREAD

**Issue by flinder** [flinder/twitter_flow#3]
When trying to change the lower bound of the speed filter I get:

`timeTravel.js:219 Uncaught TypeError: Cannot read property 'time' of undefined`

@xiliu18 can you take a look at this?

But it works awesome otherwise! Great

**Comment by xiliu18** [comment]
Yes it does not work... Because most people's min speed is 0 (I assigned 0 to NaN when calculating the speed). When we have only 20 users, changing the lower bound would lead to no users and throw out the error.

I think a good way is to set the lower bound also for the max speed, and it also makes more sense. We can discuss about this later.

**Comment by flinder** [comment]
I think the maximum speed is absolutely sufficient for filtering reasons. We could just adapt the visual so the lower bound is not available anymore. Right now, if you use it the whole filtering system breaks

**Comment by PrinzEugn** [comment]
Is there some fix without taking out the selectable lower bound? I think having the ability to set a minimum bound is important, since we can then show people who _have_ to be travelling by plane. This probably interesting for refugees, but would make it an easier sell as a broader "mining" tool.

**Comment by flinder** [comment]
@PrinzEugn that makes sense let's leave it then
